// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

#include "address.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dynamic_trace {
PROTOBUF_CONSTEXPR address::address(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.addrs_)*/{}
  , /*decltype(_impl_._addrs_cached_byte_size_)*/{0}
  , /*decltype(_impl_.data_width_)*/0
  , /*decltype(_impl_.udesc_value_)*/0u
  , /*decltype(_impl_.base_address_)*/uint64_t{0u}
  , /*decltype(_impl_.compression_format_)*/0
  , /*decltype(_impl_.stride_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct addressDefaultTypeInternal {
  PROTOBUF_CONSTEXPR addressDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~addressDefaultTypeInternal() {}
  union {
    address _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 addressDefaultTypeInternal _address_default_instance_;
}  // namespace dynamic_trace
static ::_pb::Metadata file_level_metadata_address_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_address_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_address_2eproto = nullptr;

const uint32_t TableStruct_address_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _impl_.data_width_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _impl_.udesc_value_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _impl_.compression_format_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _impl_.base_address_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _impl_.stride_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::address, _impl_.addrs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dynamic_trace::address)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dynamic_trace::_address_default_instance_._instance,
};

const char descriptor_table_protodef_address_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\raddress.proto\022\rdynamic_trace\"\203\001\n\007addre"
  "ss\022\022\n\ndata_width\030\001 \001(\005\022\023\n\013udesc_value\030\002 "
  "\001(\r\022\032\n\022compression_format\030\003 \001(\005\022\024\n\014base_"
  "address\030\004 \001(\004\022\016\n\006stride\030\005 \001(\005\022\r\n\005addrs\030\006"
  " \003(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_address_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_address_2eproto = {
    false, false, 172, descriptor_table_protodef_address_2eproto,
    "address.proto",
    &descriptor_table_address_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_address_2eproto::offsets,
    file_level_metadata_address_2eproto, file_level_enum_descriptors_address_2eproto,
    file_level_service_descriptors_address_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_address_2eproto_getter() {
  return &descriptor_table_address_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_address_2eproto(&descriptor_table_address_2eproto);
namespace dynamic_trace {

// ===================================================================

class address::_Internal {
 public:
};

address::address(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dynamic_trace.address)
}
address::address(const address& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  address* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.addrs_){from._impl_.addrs_}
    , /*decltype(_impl_._addrs_cached_byte_size_)*/{0}
    , decltype(_impl_.data_width_){}
    , decltype(_impl_.udesc_value_){}
    , decltype(_impl_.base_address_){}
    , decltype(_impl_.compression_format_){}
    , decltype(_impl_.stride_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.data_width_, &from._impl_.data_width_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.stride_) -
    reinterpret_cast<char*>(&_impl_.data_width_)) + sizeof(_impl_.stride_));
  // @@protoc_insertion_point(copy_constructor:dynamic_trace.address)
}

inline void address::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.addrs_){arena}
    , /*decltype(_impl_._addrs_cached_byte_size_)*/{0}
    , decltype(_impl_.data_width_){0}
    , decltype(_impl_.udesc_value_){0u}
    , decltype(_impl_.base_address_){uint64_t{0u}}
    , decltype(_impl_.compression_format_){0}
    , decltype(_impl_.stride_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

address::~address() {
  // @@protoc_insertion_point(destructor:dynamic_trace.address)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void address::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.addrs_.~RepeatedField();
}

void address::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void address::Clear() {
// @@protoc_insertion_point(message_clear_start:dynamic_trace.address)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.addrs_.Clear();
  ::memset(&_impl_.data_width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.stride_) -
      reinterpret_cast<char*>(&_impl_.data_width_)) + sizeof(_impl_.stride_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* address::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 data_width = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.data_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 udesc_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.udesc_value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 compression_format = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.compression_format_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 base_address = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.base_address_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 stride = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.stride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int64 addrs = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_addrs(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 48) {
          _internal_add_addrs(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* address::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dynamic_trace.address)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 data_width = 1;
  if (this->_internal_data_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_data_width(), target);
  }

  // uint32 udesc_value = 2;
  if (this->_internal_udesc_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_udesc_value(), target);
  }

  // int32 compression_format = 3;
  if (this->_internal_compression_format() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_compression_format(), target);
  }

  // uint64 base_address = 4;
  if (this->_internal_base_address() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_base_address(), target);
  }

  // int32 stride = 5;
  if (this->_internal_stride() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_stride(), target);
  }

  // repeated int64 addrs = 6;
  {
    int byte_size = _impl_._addrs_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          6, _internal_addrs(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dynamic_trace.address)
  return target;
}

size_t address::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dynamic_trace.address)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 addrs = 6;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.addrs_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._addrs_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // int32 data_width = 1;
  if (this->_internal_data_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_data_width());
  }

  // uint32 udesc_value = 2;
  if (this->_internal_udesc_value() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_udesc_value());
  }

  // uint64 base_address = 4;
  if (this->_internal_base_address() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_base_address());
  }

  // int32 compression_format = 3;
  if (this->_internal_compression_format() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_compression_format());
  }

  // int32 stride = 5;
  if (this->_internal_stride() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_stride());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData address::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    address::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*address::GetClassData() const { return &_class_data_; }


void address::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<address*>(&to_msg);
  auto& from = static_cast<const address&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dynamic_trace.address)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.addrs_.MergeFrom(from._impl_.addrs_);
  if (from._internal_data_width() != 0) {
    _this->_internal_set_data_width(from._internal_data_width());
  }
  if (from._internal_udesc_value() != 0) {
    _this->_internal_set_udesc_value(from._internal_udesc_value());
  }
  if (from._internal_base_address() != 0) {
    _this->_internal_set_base_address(from._internal_base_address());
  }
  if (from._internal_compression_format() != 0) {
    _this->_internal_set_compression_format(from._internal_compression_format());
  }
  if (from._internal_stride() != 0) {
    _this->_internal_set_stride(from._internal_stride());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void address::CopyFrom(const address& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dynamic_trace.address)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool address::IsInitialized() const {
  return true;
}

void address::InternalSwap(address* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.addrs_.InternalSwap(&other->_impl_.addrs_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(address, _impl_.stride_)
      + sizeof(address::_impl_.stride_)
      - PROTOBUF_FIELD_OFFSET(address, _impl_.data_width_)>(
          reinterpret_cast<char*>(&_impl_.data_width_),
          reinterpret_cast<char*>(&other->_impl_.data_width_));
}

::PROTOBUF_NAMESPACE_ID::Metadata address::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_address_2eproto_getter, &descriptor_table_address_2eproto_once,
      file_level_metadata_address_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dynamic_trace::address*
Arena::CreateMaybeMessage< ::dynamic_trace::address >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dynamic_trace::address >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
