// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_address_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_address_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_address_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_address_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_address_2eproto;
namespace dynamic_trace {
class address;
struct addressDefaultTypeInternal;
extern addressDefaultTypeInternal _address_default_instance_;
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> ::dynamic_trace::address* Arena::CreateMaybeMessage<::dynamic_trace::address>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dynamic_trace {

// ===================================================================

class address final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dynamic_trace.address) */ {
 public:
  inline address() : address(nullptr) {}
  ~address() override;
  explicit PROTOBUF_CONSTEXPR address(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  address(const address& from);
  address(address&& from) noexcept
    : address() {
    *this = ::std::move(from);
  }

  inline address& operator=(const address& from) {
    CopyFrom(from);
    return *this;
  }
  inline address& operator=(address&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const address& default_instance() {
    return *internal_default_instance();
  }
  static inline const address* internal_default_instance() {
    return reinterpret_cast<const address*>(
               &_address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(address& a, address& b) {
    a.Swap(&b);
  }
  inline void Swap(address* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(address* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<address>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const address& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const address& from) {
    address::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(address* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dynamic_trace.address";
  }
  protected:
  explicit address(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddrsFieldNumber = 6,
    kDataWidthFieldNumber = 1,
    kUdescValueFieldNumber = 2,
    kBaseAddressFieldNumber = 4,
    kCompressionFormatFieldNumber = 3,
    kStrideFieldNumber = 5,
  };
  // repeated int64 addrs = 6;
  int addrs_size() const;
  private:
  int _internal_addrs_size() const;
  public:
  void clear_addrs();
  private:
  int64_t _internal_addrs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_addrs() const;
  void _internal_add_addrs(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_addrs();
  public:
  int64_t addrs(int index) const;
  void set_addrs(int index, int64_t value);
  void add_addrs(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      addrs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_addrs();

  // int32 data_width = 1;
  void clear_data_width();
  int32_t data_width() const;
  void set_data_width(int32_t value);
  private:
  int32_t _internal_data_width() const;
  void _internal_set_data_width(int32_t value);
  public:

  // uint32 udesc_value = 2;
  void clear_udesc_value();
  uint32_t udesc_value() const;
  void set_udesc_value(uint32_t value);
  private:
  uint32_t _internal_udesc_value() const;
  void _internal_set_udesc_value(uint32_t value);
  public:

  // uint64 base_address = 4;
  void clear_base_address();
  uint64_t base_address() const;
  void set_base_address(uint64_t value);
  private:
  uint64_t _internal_base_address() const;
  void _internal_set_base_address(uint64_t value);
  public:

  // int32 compression_format = 3;
  void clear_compression_format();
  int32_t compression_format() const;
  void set_compression_format(int32_t value);
  private:
  int32_t _internal_compression_format() const;
  void _internal_set_compression_format(int32_t value);
  public:

  // int32 stride = 5;
  void clear_stride();
  int32_t stride() const;
  void set_stride(int32_t value);
  private:
  int32_t _internal_stride() const;
  void _internal_set_stride(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:dynamic_trace.address)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > addrs_;
    mutable std::atomic<int> _addrs_cached_byte_size_;
    int32_t data_width_;
    uint32_t udesc_value_;
    uint64_t base_address_;
    int32_t compression_format_;
    int32_t stride_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_address_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// address

// int32 data_width = 1;
inline void address::clear_data_width() {
  _impl_.data_width_ = 0;
}
inline int32_t address::_internal_data_width() const {
  return _impl_.data_width_;
}
inline int32_t address::data_width() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.address.data_width)
  return _internal_data_width();
}
inline void address::_internal_set_data_width(int32_t value) {
  
  _impl_.data_width_ = value;
}
inline void address::set_data_width(int32_t value) {
  _internal_set_data_width(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.address.data_width)
}

// uint32 udesc_value = 2;
inline void address::clear_udesc_value() {
  _impl_.udesc_value_ = 0u;
}
inline uint32_t address::_internal_udesc_value() const {
  return _impl_.udesc_value_;
}
inline uint32_t address::udesc_value() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.address.udesc_value)
  return _internal_udesc_value();
}
inline void address::_internal_set_udesc_value(uint32_t value) {
  
  _impl_.udesc_value_ = value;
}
inline void address::set_udesc_value(uint32_t value) {
  _internal_set_udesc_value(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.address.udesc_value)
}

// int32 compression_format = 3;
inline void address::clear_compression_format() {
  _impl_.compression_format_ = 0;
}
inline int32_t address::_internal_compression_format() const {
  return _impl_.compression_format_;
}
inline int32_t address::compression_format() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.address.compression_format)
  return _internal_compression_format();
}
inline void address::_internal_set_compression_format(int32_t value) {
  
  _impl_.compression_format_ = value;
}
inline void address::set_compression_format(int32_t value) {
  _internal_set_compression_format(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.address.compression_format)
}

// uint64 base_address = 4;
inline void address::clear_base_address() {
  _impl_.base_address_ = uint64_t{0u};
}
inline uint64_t address::_internal_base_address() const {
  return _impl_.base_address_;
}
inline uint64_t address::base_address() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.address.base_address)
  return _internal_base_address();
}
inline void address::_internal_set_base_address(uint64_t value) {
  
  _impl_.base_address_ = value;
}
inline void address::set_base_address(uint64_t value) {
  _internal_set_base_address(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.address.base_address)
}

// int32 stride = 5;
inline void address::clear_stride() {
  _impl_.stride_ = 0;
}
inline int32_t address::_internal_stride() const {
  return _impl_.stride_;
}
inline int32_t address::stride() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.address.stride)
  return _internal_stride();
}
inline void address::_internal_set_stride(int32_t value) {
  
  _impl_.stride_ = value;
}
inline void address::set_stride(int32_t value) {
  _internal_set_stride(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.address.stride)
}

// repeated int64 addrs = 6;
inline int address::_internal_addrs_size() const {
  return _impl_.addrs_.size();
}
inline int address::addrs_size() const {
  return _internal_addrs_size();
}
inline void address::clear_addrs() {
  _impl_.addrs_.Clear();
}
inline int64_t address::_internal_addrs(int index) const {
  return _impl_.addrs_.Get(index);
}
inline int64_t address::addrs(int index) const {
  // @@protoc_insertion_point(field_get:dynamic_trace.address.addrs)
  return _internal_addrs(index);
}
inline void address::set_addrs(int index, int64_t value) {
  _impl_.addrs_.Set(index, value);
  // @@protoc_insertion_point(field_set:dynamic_trace.address.addrs)
}
inline void address::_internal_add_addrs(int64_t value) {
  _impl_.addrs_.Add(value);
}
inline void address::add_addrs(int64_t value) {
  _internal_add_addrs(value);
  // @@protoc_insertion_point(field_add:dynamic_trace.address.addrs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
address::_internal_addrs() const {
  return _impl_.addrs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
address::addrs() const {
  // @@protoc_insertion_point(field_list:dynamic_trace.address.addrs)
  return _internal_addrs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
address::_internal_mutable_addrs() {
  return &_impl_.addrs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
address::mutable_addrs() {
  // @@protoc_insertion_point(field_mutable_list:dynamic_trace.address.addrs)
  return _internal_mutable_addrs();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace dynamic_trace

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_address_2eproto
