// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instruction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_instruction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_instruction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "address.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_instruction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_instruction_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_instruction_2eproto;
namespace dynamic_trace {
class instruction;
struct instructionDefaultTypeInternal;
extern instructionDefaultTypeInternal _instruction_default_instance_;
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> ::dynamic_trace::instruction* Arena::CreateMaybeMessage<::dynamic_trace::instruction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dynamic_trace {

// ===================================================================

class instruction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dynamic_trace.instruction) */ {
 public:
  inline instruction() : instruction(nullptr) {}
  ~instruction() override;
  explicit PROTOBUF_CONSTEXPR instruction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  instruction(const instruction& from);
  instruction(instruction&& from) noexcept
    : instruction() {
    *this = ::std::move(from);
  }

  inline instruction& operator=(const instruction& from) {
    CopyFrom(from);
    return *this;
  }
  inline instruction& operator=(instruction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const instruction& default_instance() {
    return *internal_default_instance();
  }
  static inline const instruction* internal_default_instance() {
    return reinterpret_cast<const instruction*>(
               &_instruction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(instruction& a, instruction& b) {
    a.Swap(&b);
  }
  inline void Swap(instruction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(instruction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  instruction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<instruction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const instruction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const instruction& from) {
    instruction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(instruction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dynamic_trace.instruction";
  }
  protected:
  explicit instruction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressesFieldNumber = 5,
    kPcFieldNumber = 1,
    kActiveMaskFieldNumber = 2,
    kPredicateMaskFieldNumber = 3,
    kFunctionUniqueIdFieldNumber = 4,
  };
  // repeated .dynamic_trace.address addresses = 5;
  int addresses_size() const;
  private:
  int _internal_addresses_size() const;
  public:
  void clear_addresses();
  ::dynamic_trace::address* mutable_addresses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::address >*
      mutable_addresses();
  private:
  const ::dynamic_trace::address& _internal_addresses(int index) const;
  ::dynamic_trace::address* _internal_add_addresses();
  public:
  const ::dynamic_trace::address& addresses(int index) const;
  ::dynamic_trace::address* add_addresses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::address >&
      addresses() const;

  // uint32 pc = 1;
  void clear_pc();
  uint32_t pc() const;
  void set_pc(uint32_t value);
  private:
  uint32_t _internal_pc() const;
  void _internal_set_pc(uint32_t value);
  public:

  // uint32 active_mask = 2;
  void clear_active_mask();
  uint32_t active_mask() const;
  void set_active_mask(uint32_t value);
  private:
  uint32_t _internal_active_mask() const;
  void _internal_set_active_mask(uint32_t value);
  public:

  // uint32 predicate_mask = 3;
  void clear_predicate_mask();
  uint32_t predicate_mask() const;
  void set_predicate_mask(uint32_t value);
  private:
  uint32_t _internal_predicate_mask() const;
  void _internal_set_predicate_mask(uint32_t value);
  public:

  // int32 function_unique_id = 4;
  void clear_function_unique_id();
  int32_t function_unique_id() const;
  void set_function_unique_id(int32_t value);
  private:
  int32_t _internal_function_unique_id() const;
  void _internal_set_function_unique_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:dynamic_trace.instruction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::address > addresses_;
    uint32_t pc_;
    uint32_t active_mask_;
    uint32_t predicate_mask_;
    int32_t function_unique_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_instruction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// instruction

// uint32 pc = 1;
inline void instruction::clear_pc() {
  _impl_.pc_ = 0u;
}
inline uint32_t instruction::_internal_pc() const {
  return _impl_.pc_;
}
inline uint32_t instruction::pc() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.instruction.pc)
  return _internal_pc();
}
inline void instruction::_internal_set_pc(uint32_t value) {
  
  _impl_.pc_ = value;
}
inline void instruction::set_pc(uint32_t value) {
  _internal_set_pc(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.instruction.pc)
}

// uint32 active_mask = 2;
inline void instruction::clear_active_mask() {
  _impl_.active_mask_ = 0u;
}
inline uint32_t instruction::_internal_active_mask() const {
  return _impl_.active_mask_;
}
inline uint32_t instruction::active_mask() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.instruction.active_mask)
  return _internal_active_mask();
}
inline void instruction::_internal_set_active_mask(uint32_t value) {
  
  _impl_.active_mask_ = value;
}
inline void instruction::set_active_mask(uint32_t value) {
  _internal_set_active_mask(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.instruction.active_mask)
}

// uint32 predicate_mask = 3;
inline void instruction::clear_predicate_mask() {
  _impl_.predicate_mask_ = 0u;
}
inline uint32_t instruction::_internal_predicate_mask() const {
  return _impl_.predicate_mask_;
}
inline uint32_t instruction::predicate_mask() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.instruction.predicate_mask)
  return _internal_predicate_mask();
}
inline void instruction::_internal_set_predicate_mask(uint32_t value) {
  
  _impl_.predicate_mask_ = value;
}
inline void instruction::set_predicate_mask(uint32_t value) {
  _internal_set_predicate_mask(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.instruction.predicate_mask)
}

// int32 function_unique_id = 4;
inline void instruction::clear_function_unique_id() {
  _impl_.function_unique_id_ = 0;
}
inline int32_t instruction::_internal_function_unique_id() const {
  return _impl_.function_unique_id_;
}
inline int32_t instruction::function_unique_id() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.instruction.function_unique_id)
  return _internal_function_unique_id();
}
inline void instruction::_internal_set_function_unique_id(int32_t value) {
  
  _impl_.function_unique_id_ = value;
}
inline void instruction::set_function_unique_id(int32_t value) {
  _internal_set_function_unique_id(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.instruction.function_unique_id)
}

// repeated .dynamic_trace.address addresses = 5;
inline int instruction::_internal_addresses_size() const {
  return _impl_.addresses_.size();
}
inline int instruction::addresses_size() const {
  return _internal_addresses_size();
}
inline ::dynamic_trace::address* instruction::mutable_addresses(int index) {
  // @@protoc_insertion_point(field_mutable:dynamic_trace.instruction.addresses)
  return _impl_.addresses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::address >*
instruction::mutable_addresses() {
  // @@protoc_insertion_point(field_mutable_list:dynamic_trace.instruction.addresses)
  return &_impl_.addresses_;
}
inline const ::dynamic_trace::address& instruction::_internal_addresses(int index) const {
  return _impl_.addresses_.Get(index);
}
inline const ::dynamic_trace::address& instruction::addresses(int index) const {
  // @@protoc_insertion_point(field_get:dynamic_trace.instruction.addresses)
  return _internal_addresses(index);
}
inline ::dynamic_trace::address* instruction::_internal_add_addresses() {
  return _impl_.addresses_.Add();
}
inline ::dynamic_trace::address* instruction::add_addresses() {
  ::dynamic_trace::address* _add = _internal_add_addresses();
  // @@protoc_insertion_point(field_add:dynamic_trace.instruction.addresses)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::address >&
instruction::addresses() const {
  // @@protoc_insertion_point(field_list:dynamic_trace.instruction.addresses)
  return _impl_.addresses_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace dynamic_trace

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_instruction_2eproto
