// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instruction.proto

#include "instruction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dynamic_trace {
PROTOBUF_CONSTEXPR instruction::instruction(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.addresses_)*/{}
  , /*decltype(_impl_.pc_)*/0u
  , /*decltype(_impl_.active_mask_)*/0u
  , /*decltype(_impl_.predicate_mask_)*/0u
  , /*decltype(_impl_.function_unique_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct instructionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR instructionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~instructionDefaultTypeInternal() {}
  union {
    instruction _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 instructionDefaultTypeInternal _instruction_default_instance_;
}  // namespace dynamic_trace
static ::_pb::Metadata file_level_metadata_instruction_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_instruction_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_instruction_2eproto = nullptr;

const uint32_t TableStruct_instruction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::instruction, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::instruction, _impl_.pc_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::instruction, _impl_.active_mask_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::instruction, _impl_.predicate_mask_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::instruction, _impl_.function_unique_id_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::instruction, _impl_.addresses_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dynamic_trace::instruction)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dynamic_trace::_instruction_default_instance_._instance,
};

const char descriptor_table_protodef_instruction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021instruction.proto\022\rdynamic_trace\032\raddr"
  "ess.proto\"\215\001\n\013instruction\022\n\n\002pc\030\001 \001(\r\022\023\n"
  "\013active_mask\030\002 \001(\r\022\026\n\016predicate_mask\030\003 \001"
  "(\r\022\032\n\022function_unique_id\030\004 \001(\005\022)\n\taddres"
  "ses\030\005 \003(\0132\026.dynamic_trace.addressb\006proto"
  "3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_instruction_2eproto_deps[1] = {
  &::descriptor_table_address_2eproto,
};
static ::_pbi::once_flag descriptor_table_instruction_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_instruction_2eproto = {
    false, false, 201, descriptor_table_protodef_instruction_2eproto,
    "instruction.proto",
    &descriptor_table_instruction_2eproto_once, descriptor_table_instruction_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_instruction_2eproto::offsets,
    file_level_metadata_instruction_2eproto, file_level_enum_descriptors_instruction_2eproto,
    file_level_service_descriptors_instruction_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_instruction_2eproto_getter() {
  return &descriptor_table_instruction_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_instruction_2eproto(&descriptor_table_instruction_2eproto);
namespace dynamic_trace {

// ===================================================================

class instruction::_Internal {
 public:
};

void instruction::clear_addresses() {
  _impl_.addresses_.Clear();
}
instruction::instruction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dynamic_trace.instruction)
}
instruction::instruction(const instruction& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  instruction* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.addresses_){from._impl_.addresses_}
    , decltype(_impl_.pc_){}
    , decltype(_impl_.active_mask_){}
    , decltype(_impl_.predicate_mask_){}
    , decltype(_impl_.function_unique_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.pc_, &from._impl_.pc_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.function_unique_id_) -
    reinterpret_cast<char*>(&_impl_.pc_)) + sizeof(_impl_.function_unique_id_));
  // @@protoc_insertion_point(copy_constructor:dynamic_trace.instruction)
}

inline void instruction::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.addresses_){arena}
    , decltype(_impl_.pc_){0u}
    , decltype(_impl_.active_mask_){0u}
    , decltype(_impl_.predicate_mask_){0u}
    , decltype(_impl_.function_unique_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

instruction::~instruction() {
  // @@protoc_insertion_point(destructor:dynamic_trace.instruction)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void instruction::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.addresses_.~RepeatedPtrField();
}

void instruction::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void instruction::Clear() {
// @@protoc_insertion_point(message_clear_start:dynamic_trace.instruction)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.addresses_.Clear();
  ::memset(&_impl_.pc_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.function_unique_id_) -
      reinterpret_cast<char*>(&_impl_.pc_)) + sizeof(_impl_.function_unique_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* instruction::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 pc = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.pc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 active_mask = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.active_mask_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 predicate_mask = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.predicate_mask_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 function_unique_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.function_unique_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .dynamic_trace.address addresses = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_addresses(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* instruction::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dynamic_trace.instruction)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 pc = 1;
  if (this->_internal_pc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_pc(), target);
  }

  // uint32 active_mask = 2;
  if (this->_internal_active_mask() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_active_mask(), target);
  }

  // uint32 predicate_mask = 3;
  if (this->_internal_predicate_mask() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_predicate_mask(), target);
  }

  // int32 function_unique_id = 4;
  if (this->_internal_function_unique_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_function_unique_id(), target);
  }

  // repeated .dynamic_trace.address addresses = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_addresses_size()); i < n; i++) {
    const auto& repfield = this->_internal_addresses(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dynamic_trace.instruction)
  return target;
}

size_t instruction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dynamic_trace.instruction)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .dynamic_trace.address addresses = 5;
  total_size += 1UL * this->_internal_addresses_size();
  for (const auto& msg : this->_impl_.addresses_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 pc = 1;
  if (this->_internal_pc() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_pc());
  }

  // uint32 active_mask = 2;
  if (this->_internal_active_mask() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_active_mask());
  }

  // uint32 predicate_mask = 3;
  if (this->_internal_predicate_mask() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_predicate_mask());
  }

  // int32 function_unique_id = 4;
  if (this->_internal_function_unique_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_function_unique_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData instruction::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    instruction::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*instruction::GetClassData() const { return &_class_data_; }


void instruction::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<instruction*>(&to_msg);
  auto& from = static_cast<const instruction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dynamic_trace.instruction)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.addresses_.MergeFrom(from._impl_.addresses_);
  if (from._internal_pc() != 0) {
    _this->_internal_set_pc(from._internal_pc());
  }
  if (from._internal_active_mask() != 0) {
    _this->_internal_set_active_mask(from._internal_active_mask());
  }
  if (from._internal_predicate_mask() != 0) {
    _this->_internal_set_predicate_mask(from._internal_predicate_mask());
  }
  if (from._internal_function_unique_id() != 0) {
    _this->_internal_set_function_unique_id(from._internal_function_unique_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void instruction::CopyFrom(const instruction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dynamic_trace.instruction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool instruction::IsInitialized() const {
  return true;
}

void instruction::InternalSwap(instruction* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.addresses_.InternalSwap(&other->_impl_.addresses_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(instruction, _impl_.function_unique_id_)
      + sizeof(instruction::_impl_.function_unique_id_)
      - PROTOBUF_FIELD_OFFSET(instruction, _impl_.pc_)>(
          reinterpret_cast<char*>(&_impl_.pc_),
          reinterpret_cast<char*>(&other->_impl_.pc_));
}

::PROTOBUF_NAMESPACE_ID::Metadata instruction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_instruction_2eproto_getter, &descriptor_table_instruction_2eproto_once,
      file_level_metadata_instruction_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dynamic_trace::instruction*
Arena::CreateMaybeMessage< ::dynamic_trace::instruction >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dynamic_trace::instruction >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
