// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: threadblock.proto

#include "threadblock.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dynamic_trace {
PROTOBUF_CONSTEXPR threadblock_WarpsEntry_DoNotUse::threadblock_WarpsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct threadblock_WarpsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR threadblock_WarpsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~threadblock_WarpsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    threadblock_WarpsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 threadblock_WarpsEntry_DoNotUseDefaultTypeInternal _threadblock_WarpsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR threadblock::threadblock(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.warps_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.block_id_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct threadblockDefaultTypeInternal {
  PROTOBUF_CONSTEXPR threadblockDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~threadblockDefaultTypeInternal() {}
  union {
    threadblock _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 threadblockDefaultTypeInternal _threadblock_default_instance_;
}  // namespace dynamic_trace
static ::_pb::Metadata file_level_metadata_threadblock_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_threadblock_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_threadblock_2eproto = nullptr;

const uint32_t TableStruct_threadblock_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock_WarpsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock_WarpsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock_WarpsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock_WarpsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock, _impl_.block_id_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::threadblock, _impl_.warps_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::dynamic_trace::threadblock_WarpsEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::dynamic_trace::threadblock)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dynamic_trace::_threadblock_WarpsEntry_DoNotUse_default_instance_._instance,
  &::dynamic_trace::_threadblock_default_instance_._instance,
};

const char descriptor_table_protodef_threadblock_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021threadblock.proto\022\rdynamic_trace\032\nwarp"
  ".proto\032\013dim3d.proto\"\256\001\n\013threadblock\022&\n\010b"
  "lock_id\030\001 \001(\0132\024.dynamic_trace.dim3d\0224\n\005w"
  "arps\030\002 \003(\0132%.dynamic_trace.threadblock.W"
  "arpsEntry\032A\n\nWarpsEntry\022\013\n\003key\030\001 \001(\005\022\"\n\005"
  "value\030\002 \001(\0132\023.dynamic_trace.warp:\0028\001b\006pr"
  "oto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_threadblock_2eproto_deps[2] = {
  &::descriptor_table_dim3d_2eproto,
  &::descriptor_table_warp_2eproto,
};
static ::_pbi::once_flag descriptor_table_threadblock_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_threadblock_2eproto = {
    false, false, 244, descriptor_table_protodef_threadblock_2eproto,
    "threadblock.proto",
    &descriptor_table_threadblock_2eproto_once, descriptor_table_threadblock_2eproto_deps, 2, 2,
    schemas, file_default_instances, TableStruct_threadblock_2eproto::offsets,
    file_level_metadata_threadblock_2eproto, file_level_enum_descriptors_threadblock_2eproto,
    file_level_service_descriptors_threadblock_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_threadblock_2eproto_getter() {
  return &descriptor_table_threadblock_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_threadblock_2eproto(&descriptor_table_threadblock_2eproto);
namespace dynamic_trace {

// ===================================================================

threadblock_WarpsEntry_DoNotUse::threadblock_WarpsEntry_DoNotUse() {}
threadblock_WarpsEntry_DoNotUse::threadblock_WarpsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void threadblock_WarpsEntry_DoNotUse::MergeFrom(const threadblock_WarpsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata threadblock_WarpsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_threadblock_2eproto_getter, &descriptor_table_threadblock_2eproto_once,
      file_level_metadata_threadblock_2eproto[0]);
}

// ===================================================================

class threadblock::_Internal {
 public:
  static const ::dynamic_trace::dim3d& block_id(const threadblock* msg);
};

const ::dynamic_trace::dim3d&
threadblock::_Internal::block_id(const threadblock* msg) {
  return *msg->_impl_.block_id_;
}
void threadblock::clear_block_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.block_id_ != nullptr) {
    delete _impl_.block_id_;
  }
  _impl_.block_id_ = nullptr;
}
void threadblock::clear_warps() {
  _impl_.warps_.Clear();
}
threadblock::threadblock(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &threadblock::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:dynamic_trace.threadblock)
}
threadblock::threadblock(const threadblock& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  threadblock* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.warps_)*/{}
    , decltype(_impl_.block_id_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.warps_.MergeFrom(from._impl_.warps_);
  if (from._internal_has_block_id()) {
    _this->_impl_.block_id_ = new ::dynamic_trace::dim3d(*from._impl_.block_id_);
  }
  // @@protoc_insertion_point(copy_constructor:dynamic_trace.threadblock)
}

inline void threadblock::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.warps_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.block_id_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

threadblock::~threadblock() {
  // @@protoc_insertion_point(destructor:dynamic_trace.threadblock)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void threadblock::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.warps_.Destruct();
  _impl_.warps_.~MapField();
  if (this != internal_default_instance()) delete _impl_.block_id_;
}

void threadblock::ArenaDtor(void* object) {
  threadblock* _this = reinterpret_cast< threadblock* >(object);
  _this->_impl_.warps_.Destruct();
}
void threadblock::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void threadblock::Clear() {
// @@protoc_insertion_point(message_clear_start:dynamic_trace.threadblock)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.warps_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.block_id_ != nullptr) {
    delete _impl_.block_id_;
  }
  _impl_.block_id_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* threadblock::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .dynamic_trace.dim3d block_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_block_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<int32, .dynamic_trace.warp> warps = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.warps_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* threadblock::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dynamic_trace.threadblock)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .dynamic_trace.dim3d block_id = 1;
  if (this->_internal_has_block_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::block_id(this),
        _Internal::block_id(this).GetCachedSize(), target, stream);
  }

  // map<int32, .dynamic_trace.warp> warps = 2;
  if (!this->_internal_warps().empty()) {
    using MapType = ::_pb::Map<int32_t, ::dynamic_trace::warp>;
    using WireHelper = threadblock_WarpsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_warps();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(2, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(2, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dynamic_trace.threadblock)
  return target;
}

size_t threadblock::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dynamic_trace.threadblock)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .dynamic_trace.warp> warps = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_warps_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >::const_iterator
      it = this->_internal_warps().begin();
      it != this->_internal_warps().end(); ++it) {
    total_size += threadblock_WarpsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .dynamic_trace.dim3d block_id = 1;
  if (this->_internal_has_block_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.block_id_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData threadblock::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    threadblock::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*threadblock::GetClassData() const { return &_class_data_; }


void threadblock::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<threadblock*>(&to_msg);
  auto& from = static_cast<const threadblock&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dynamic_trace.threadblock)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.warps_.MergeFrom(from._impl_.warps_);
  if (from._internal_has_block_id()) {
    _this->_internal_mutable_block_id()->::dynamic_trace::dim3d::MergeFrom(
        from._internal_block_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void threadblock::CopyFrom(const threadblock& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dynamic_trace.threadblock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool threadblock::IsInitialized() const {
  return true;
}

void threadblock::InternalSwap(threadblock* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.warps_.InternalSwap(&other->_impl_.warps_);
  swap(_impl_.block_id_, other->_impl_.block_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata threadblock::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_threadblock_2eproto_getter, &descriptor_table_threadblock_2eproto_once,
      file_level_metadata_threadblock_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dynamic_trace::threadblock_WarpsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::dynamic_trace::threadblock_WarpsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dynamic_trace::threadblock_WarpsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::dynamic_trace::threadblock*
Arena::CreateMaybeMessage< ::dynamic_trace::threadblock >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dynamic_trace::threadblock >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
