// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: threadblock.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_threadblock_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_threadblock_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "warp.pb.h"
#include "dim3d.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_threadblock_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_threadblock_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_threadblock_2eproto;
namespace dynamic_trace {
class threadblock;
struct threadblockDefaultTypeInternal;
extern threadblockDefaultTypeInternal _threadblock_default_instance_;
class threadblock_WarpsEntry_DoNotUse;
struct threadblock_WarpsEntry_DoNotUseDefaultTypeInternal;
extern threadblock_WarpsEntry_DoNotUseDefaultTypeInternal _threadblock_WarpsEntry_DoNotUse_default_instance_;
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> ::dynamic_trace::threadblock* Arena::CreateMaybeMessage<::dynamic_trace::threadblock>(Arena*);
template<> ::dynamic_trace::threadblock_WarpsEntry_DoNotUse* Arena::CreateMaybeMessage<::dynamic_trace::threadblock_WarpsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dynamic_trace {

// ===================================================================

class threadblock_WarpsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<threadblock_WarpsEntry_DoNotUse, 
    int32_t, ::dynamic_trace::warp,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<threadblock_WarpsEntry_DoNotUse, 
    int32_t, ::dynamic_trace::warp,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  threadblock_WarpsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR threadblock_WarpsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit threadblock_WarpsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const threadblock_WarpsEntry_DoNotUse& other);
  static const threadblock_WarpsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const threadblock_WarpsEntry_DoNotUse*>(&_threadblock_WarpsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_threadblock_2eproto;
};

// -------------------------------------------------------------------

class threadblock final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dynamic_trace.threadblock) */ {
 public:
  inline threadblock() : threadblock(nullptr) {}
  ~threadblock() override;
  explicit PROTOBUF_CONSTEXPR threadblock(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  threadblock(const threadblock& from);
  threadblock(threadblock&& from) noexcept
    : threadblock() {
    *this = ::std::move(from);
  }

  inline threadblock& operator=(const threadblock& from) {
    CopyFrom(from);
    return *this;
  }
  inline threadblock& operator=(threadblock&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const threadblock& default_instance() {
    return *internal_default_instance();
  }
  static inline const threadblock* internal_default_instance() {
    return reinterpret_cast<const threadblock*>(
               &_threadblock_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(threadblock& a, threadblock& b) {
    a.Swap(&b);
  }
  inline void Swap(threadblock* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(threadblock* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  threadblock* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<threadblock>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const threadblock& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const threadblock& from) {
    threadblock::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(threadblock* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dynamic_trace.threadblock";
  }
  protected:
  explicit threadblock(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kWarpsFieldNumber = 2,
    kBlockIdFieldNumber = 1,
  };
  // map<int32, .dynamic_trace.warp> warps = 2;
  int warps_size() const;
  private:
  int _internal_warps_size() const;
  public:
  void clear_warps();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >&
      _internal_warps() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >*
      _internal_mutable_warps();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >&
      warps() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >*
      mutable_warps();

  // .dynamic_trace.dim3d block_id = 1;
  bool has_block_id() const;
  private:
  bool _internal_has_block_id() const;
  public:
  void clear_block_id();
  const ::dynamic_trace::dim3d& block_id() const;
  PROTOBUF_NODISCARD ::dynamic_trace::dim3d* release_block_id();
  ::dynamic_trace::dim3d* mutable_block_id();
  void set_allocated_block_id(::dynamic_trace::dim3d* block_id);
  private:
  const ::dynamic_trace::dim3d& _internal_block_id() const;
  ::dynamic_trace::dim3d* _internal_mutable_block_id();
  public:
  void unsafe_arena_set_allocated_block_id(
      ::dynamic_trace::dim3d* block_id);
  ::dynamic_trace::dim3d* unsafe_arena_release_block_id();

  // @@protoc_insertion_point(class_scope:dynamic_trace.threadblock)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        threadblock_WarpsEntry_DoNotUse,
        int32_t, ::dynamic_trace::warp,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> warps_;
    ::dynamic_trace::dim3d* block_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_threadblock_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// threadblock

// .dynamic_trace.dim3d block_id = 1;
inline bool threadblock::_internal_has_block_id() const {
  return this != internal_default_instance() && _impl_.block_id_ != nullptr;
}
inline bool threadblock::has_block_id() const {
  return _internal_has_block_id();
}
inline const ::dynamic_trace::dim3d& threadblock::_internal_block_id() const {
  const ::dynamic_trace::dim3d* p = _impl_.block_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::dynamic_trace::dim3d&>(
      ::dynamic_trace::_dim3d_default_instance_);
}
inline const ::dynamic_trace::dim3d& threadblock::block_id() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.threadblock.block_id)
  return _internal_block_id();
}
inline void threadblock::unsafe_arena_set_allocated_block_id(
    ::dynamic_trace::dim3d* block_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.block_id_);
  }
  _impl_.block_id_ = block_id;
  if (block_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dynamic_trace.threadblock.block_id)
}
inline ::dynamic_trace::dim3d* threadblock::release_block_id() {
  
  ::dynamic_trace::dim3d* temp = _impl_.block_id_;
  _impl_.block_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dynamic_trace::dim3d* threadblock::unsafe_arena_release_block_id() {
  // @@protoc_insertion_point(field_release:dynamic_trace.threadblock.block_id)
  
  ::dynamic_trace::dim3d* temp = _impl_.block_id_;
  _impl_.block_id_ = nullptr;
  return temp;
}
inline ::dynamic_trace::dim3d* threadblock::_internal_mutable_block_id() {
  
  if (_impl_.block_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::dynamic_trace::dim3d>(GetArenaForAllocation());
    _impl_.block_id_ = p;
  }
  return _impl_.block_id_;
}
inline ::dynamic_trace::dim3d* threadblock::mutable_block_id() {
  ::dynamic_trace::dim3d* _msg = _internal_mutable_block_id();
  // @@protoc_insertion_point(field_mutable:dynamic_trace.threadblock.block_id)
  return _msg;
}
inline void threadblock::set_allocated_block_id(::dynamic_trace::dim3d* block_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.block_id_);
  }
  if (block_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(block_id));
    if (message_arena != submessage_arena) {
      block_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, block_id, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.block_id_ = block_id;
  // @@protoc_insertion_point(field_set_allocated:dynamic_trace.threadblock.block_id)
}

// map<int32, .dynamic_trace.warp> warps = 2;
inline int threadblock::_internal_warps_size() const {
  return _impl_.warps_.size();
}
inline int threadblock::warps_size() const {
  return _internal_warps_size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >&
threadblock::_internal_warps() const {
  return _impl_.warps_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >&
threadblock::warps() const {
  // @@protoc_insertion_point(field_map:dynamic_trace.threadblock.warps)
  return _internal_warps();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >*
threadblock::_internal_mutable_warps() {
  return _impl_.warps_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::dynamic_trace::warp >*
threadblock::mutable_warps() {
  // @@protoc_insertion_point(field_mutable_map:dynamic_trace.threadblock.warps)
  return _internal_mutable_warps();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dynamic_trace

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_threadblock_2eproto
