// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trace.proto
// Protobuf C++ Version: 5.28.2

#include "trace.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dynamic_trace {
              template <typename>
PROTOBUF_CONSTEXPR Trace_GpuDeviceEntry_DoNotUse::Trace_GpuDeviceEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Trace_GpuDeviceEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Trace_GpuDeviceEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Trace_GpuDeviceEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Trace_GpuDeviceEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Trace_GpuDeviceEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Trace_GpuDeviceEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Trace_GpuDeviceEntry_DoNotUseDefaultTypeInternal _Trace_GpuDeviceEntry_DoNotUse_default_instance_;

inline constexpr Trace::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : gpu_device_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        nvbit_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        binary_version_{0},
        accelsim_version_{0},
        is_gathered_registers_values_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Trace::Trace(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TraceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TraceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TraceDefaultTypeInternal() {}
  union {
    Trace _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TraceDefaultTypeInternal _Trace_default_instance_;
}  // namespace dynamic_trace
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_trace_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_trace_2eproto = nullptr;
const ::uint32_t
    TableStruct_trace_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace_GpuDeviceEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace_GpuDeviceEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace_GpuDeviceEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace_GpuDeviceEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _impl_.binary_version_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _impl_.nvbit_version_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _impl_.accelsim_version_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _impl_.is_gathered_registers_values_),
        PROTOBUF_FIELD_OFFSET(::dynamic_trace::Trace, _impl_.gpu_device_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::dynamic_trace::Trace_GpuDeviceEntry_DoNotUse)},
        {12, -1, -1, sizeof(::dynamic_trace::Trace)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::dynamic_trace::_Trace_GpuDeviceEntry_DoNotUse_default_instance_._instance,
    &::dynamic_trace::_Trace_default_instance_._instance,
};
const char descriptor_table_protodef_trace_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013trace.proto\022\rdynamic_trace\032\020gpu_device"
    ".proto\"\212\002\n\005Trace\022\014\n\004name\030\001 \001(\t\022\026\n\016binary"
    "_version\030\002 \001(\005\022\025\n\rnvbit_version\030\003 \001(\t\022\030\n"
    "\020accelsim_version\030\004 \001(\005\022$\n\034is_gathered_r"
    "egisters_values\030\005 \001(\010\0227\n\ngpu_device\030\006 \003("
    "\0132#.dynamic_trace.Trace.GpuDeviceEntry\032K"
    "\n\016GpuDeviceEntry\022\013\n\003key\030\001 \001(\003\022(\n\005value\030\002"
    " \001(\0132\031.dynamic_trace.gpu_device:\0028\001b\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_trace_2eproto_deps[1] =
    {
        &::descriptor_table_gpu_5fdevice_2eproto,
};
static ::absl::once_flag descriptor_table_trace_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_trace_2eproto = {
    false,
    false,
    323,
    descriptor_table_protodef_trace_2eproto,
    "trace.proto",
    &descriptor_table_trace_2eproto_once,
    descriptor_table_trace_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_trace_2eproto::offsets,
    file_level_enum_descriptors_trace_2eproto,
    file_level_service_descriptors_trace_2eproto,
};
namespace dynamic_trace {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              Trace_GpuDeviceEntry_DoNotUse::Trace_GpuDeviceEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              Trace_GpuDeviceEntry_DoNotUse::Trace_GpuDeviceEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              Trace_GpuDeviceEntry_DoNotUse::Trace_GpuDeviceEntry_DoNotUse() : SuperType() {}
              Trace_GpuDeviceEntry_DoNotUse::Trace_GpuDeviceEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::MessageLite::ClassDataFull
                  Trace_GpuDeviceEntry_DoNotUse::_class_data_ = {
                      ::google::protobuf::Message::ClassData{
                          &_Trace_GpuDeviceEntry_DoNotUse_default_instance_._instance,
                          &_table_.header,
                          nullptr,  // OnDemandRegisterArenaDtor
                          nullptr,  // IsInitialized
                          &Trace_GpuDeviceEntry_DoNotUse::MergeImpl,
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                          ::google::protobuf::Message::GetDeleteImpl<Trace_GpuDeviceEntry_DoNotUse>(),
                          ::google::protobuf::Message::GetNewImpl<Trace_GpuDeviceEntry_DoNotUse>(),
                          ::google::protobuf::Message::ClearImpl, ::google::protobuf::Message::ByteSizeLongImpl,
                              ::google::protobuf::Message::_InternalSerializeImpl,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                          PROTOBUF_FIELD_OFFSET(Trace_GpuDeviceEntry_DoNotUse, _impl_._cached_size_),
                          false,
                      },
                      &Trace_GpuDeviceEntry_DoNotUse::kDescriptorMethods,
                      &descriptor_table_trace_2eproto,
                      nullptr,  // tracker
              };
              const ::google::protobuf::MessageLite::ClassData* Trace_GpuDeviceEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> Trace_GpuDeviceEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Trace_GpuDeviceEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dynamic_trace::Trace_GpuDeviceEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .dynamic_trace.gpu_device value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Trace_GpuDeviceEntry_DoNotUse, _impl_.value_)}},
    // int64 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Trace_GpuDeviceEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Trace_GpuDeviceEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 key = 1;
    {PROTOBUF_FIELD_OFFSET(Trace_GpuDeviceEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .dynamic_trace.gpu_device value = 2;
    {PROTOBUF_FIELD_OFFSET(Trace_GpuDeviceEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::dynamic_trace::gpu_device>()},
  }}, {{
  }},
};

// ===================================================================

class Trace::_Internal {
 public:
};

void Trace::clear_gpu_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpu_device_.Clear();
}
Trace::Trace(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dynamic_trace.Trace)
}
inline PROTOBUF_NDEBUG_INLINE Trace::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dynamic_trace::Trace& from_msg)
      : gpu_device_{visibility, arena, from.gpu_device_},
        name_(arena, from.name_),
        nvbit_version_(arena, from.nvbit_version_),
        _cached_size_{0} {}

Trace::Trace(
    ::google::protobuf::Arena* arena,
    const Trace& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Trace* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, binary_version_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, binary_version_),
           offsetof(Impl_, is_gathered_registers_values_) -
               offsetof(Impl_, binary_version_) +
               sizeof(Impl_::is_gathered_registers_values_));

  // @@protoc_insertion_point(copy_constructor:dynamic_trace.Trace)
}
inline PROTOBUF_NDEBUG_INLINE Trace::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : gpu_device_{visibility, arena},
        name_(arena),
        nvbit_version_(arena),
        _cached_size_{0} {}

inline void Trace::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, binary_version_),
           0,
           offsetof(Impl_, is_gathered_registers_values_) -
               offsetof(Impl_, binary_version_) +
               sizeof(Impl_::is_gathered_registers_values_));
}
Trace::~Trace() {
  // @@protoc_insertion_point(destructor:dynamic_trace.Trace)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Trace::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.nvbit_version_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Trace::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Trace_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Trace::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Trace>(),
            ::google::protobuf::Message::GetNewImpl<Trace>(),
            ::google::protobuf::Message::GetClearImpl<Trace>(), &Trace::ByteSizeLong,
                &Trace::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Trace, _impl_._cached_size_),
            false,
        },
        &Trace::kDescriptorMethods,
        &descriptor_table_trace_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Trace::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 45, 2> Trace::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dynamic_trace::Trace>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Trace, _impl_.name_)}},
    // int32 binary_version = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Trace, _impl_.binary_version_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Trace, _impl_.binary_version_)}},
    // string nvbit_version = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Trace, _impl_.nvbit_version_)}},
    // int32 accelsim_version = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Trace, _impl_.accelsim_version_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Trace, _impl_.accelsim_version_)}},
    // bool is_gathered_registers_values = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Trace, _impl_.is_gathered_registers_values_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Trace, _impl_.is_gathered_registers_values_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Trace, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 binary_version = 2;
    {PROTOBUF_FIELD_OFFSET(Trace, _impl_.binary_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string nvbit_version = 3;
    {PROTOBUF_FIELD_OFFSET(Trace, _impl_.nvbit_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 accelsim_version = 4;
    {PROTOBUF_FIELD_OFFSET(Trace, _impl_.accelsim_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool is_gathered_registers_values = 5;
    {PROTOBUF_FIELD_OFFSET(Trace, _impl_.is_gathered_registers_values_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // map<int64, .dynamic_trace.gpu_device> gpu_device = 6;
    {PROTOBUF_FIELD_OFFSET(Trace, _impl_.gpu_device_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Trace()._impl_.gpu_device_)>(
        0, 0, 0, 3,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::dynamic_trace::gpu_device>},
  }}, {{
    "\23\4\0\15\0\0\0\0"
    "dynamic_trace.Trace"
    "name"
    "nvbit_version"
  }},
};

PROTOBUF_NOINLINE void Trace::Clear() {
// @@protoc_insertion_point(message_clear_start:dynamic_trace.Trace)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gpu_device_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.nvbit_version_.ClearToEmpty();
  ::memset(&_impl_.binary_version_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_gathered_registers_values_) -
      reinterpret_cast<char*>(&_impl_.binary_version_)) + sizeof(_impl_.is_gathered_registers_values_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Trace::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Trace& this_ = static_cast<const Trace&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Trace::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Trace& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dynamic_trace.Trace)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dynamic_trace.Trace.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 binary_version = 2;
          if (this_._internal_binary_version() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_binary_version(), target);
          }

          // string nvbit_version = 3;
          if (!this_._internal_nvbit_version().empty()) {
            const std::string& _s = this_._internal_nvbit_version();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dynamic_trace.Trace.nvbit_version");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // int32 accelsim_version = 4;
          if (this_._internal_accelsim_version() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_accelsim_version(), target);
          }

          // bool is_gathered_registers_values = 5;
          if (this_._internal_is_gathered_registers_values() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_is_gathered_registers_values(), target);
          }

          // map<int64, .dynamic_trace.gpu_device> gpu_device = 6;
          if (!this_._internal_gpu_device().empty()) {
            using MapType = ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>;
            using WireHelper = _pbi::MapEntryFuncs<::int64_t, ::dynamic_trace::gpu_device,
                                           _pbi::WireFormatLite::TYPE_INT64,
                                           _pbi::WireFormatLite::TYPE_MESSAGE>;
            const auto& field = this_._internal_gpu_device();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    6, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    6, entry.first, entry.second, target, stream);
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dynamic_trace.Trace)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Trace::ByteSizeLong(const MessageLite& base) {
          const Trace& this_ = static_cast<const Trace&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Trace::ByteSizeLong() const {
          const Trace& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dynamic_trace.Trace)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<int64, .dynamic_trace.gpu_device> gpu_device = 6;
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_gpu_device_size());
              for (const auto& entry : this_._internal_gpu_device()) {
                total_size += _pbi::MapEntryFuncs<::int64_t, ::dynamic_trace::gpu_device,
                                               _pbi::WireFormatLite::TYPE_INT64,
                                               _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // string nvbit_version = 3;
            if (!this_._internal_nvbit_version().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_nvbit_version());
            }
            // int32 binary_version = 2;
            if (this_._internal_binary_version() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_binary_version());
            }
            // int32 accelsim_version = 4;
            if (this_._internal_accelsim_version() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_accelsim_version());
            }
            // bool is_gathered_registers_values = 5;
            if (this_._internal_is_gathered_registers_values() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Trace::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Trace*>(&to_msg);
  auto& from = static_cast<const Trace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dynamic_trace.Trace)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.gpu_device_.MergeFrom(from._impl_.gpu_device_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_nvbit_version().empty()) {
    _this->_internal_set_nvbit_version(from._internal_nvbit_version());
  }
  if (from._internal_binary_version() != 0) {
    _this->_impl_.binary_version_ = from._impl_.binary_version_;
  }
  if (from._internal_accelsim_version() != 0) {
    _this->_impl_.accelsim_version_ = from._impl_.accelsim_version_;
  }
  if (from._internal_is_gathered_registers_values() != 0) {
    _this->_impl_.is_gathered_registers_values_ = from._impl_.is_gathered_registers_values_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Trace::CopyFrom(const Trace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dynamic_trace.Trace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Trace::InternalSwap(Trace* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.gpu_device_.InternalSwap(&other->_impl_.gpu_device_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nvbit_version_, &other->_impl_.nvbit_version_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Trace, _impl_.is_gathered_registers_values_)
      + sizeof(Trace::_impl_.is_gathered_registers_values_)
      - PROTOBUF_FIELD_OFFSET(Trace, _impl_.binary_version_)>(
          reinterpret_cast<char*>(&_impl_.binary_version_),
          reinterpret_cast<char*>(&other->_impl_.binary_version_));
}

::google::protobuf::Metadata Trace::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace dynamic_trace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_trace_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
