// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: trace.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_trace_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_trace_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
#include "gpu_device.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_trace_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_trace_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_trace_2eproto;
namespace dynamic_trace {
class Trace;
struct TraceDefaultTypeInternal;
extern TraceDefaultTypeInternal _Trace_default_instance_;
class Trace_GpuDeviceEntry_DoNotUse;
struct Trace_GpuDeviceEntry_DoNotUseDefaultTypeInternal;
extern Trace_GpuDeviceEntry_DoNotUseDefaultTypeInternal _Trace_GpuDeviceEntry_DoNotUse_default_instance_;
}  // namespace dynamic_trace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace dynamic_trace {

// ===================================================================


// -------------------------------------------------------------------

class Trace_GpuDeviceEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          Trace_GpuDeviceEntry_DoNotUse, ::int64_t, ::dynamic_trace::gpu_device,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      Trace_GpuDeviceEntry_DoNotUse, ::int64_t, ::dynamic_trace::gpu_device,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  Trace_GpuDeviceEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Trace_GpuDeviceEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Trace_GpuDeviceEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Trace_GpuDeviceEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Trace_GpuDeviceEntry_DoNotUse*>(
        &_Trace_GpuDeviceEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_trace_2eproto;
};
// -------------------------------------------------------------------

class Trace final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dynamic_trace.Trace) */ {
 public:
  inline Trace() : Trace(nullptr) {}
  ~Trace() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Trace(
      ::google::protobuf::internal::ConstantInitialized);

  inline Trace(const Trace& from) : Trace(nullptr, from) {}
  inline Trace(Trace&& from) noexcept
      : Trace(nullptr, std::move(from)) {}
  inline Trace& operator=(const Trace& from) {
    CopyFrom(from);
    return *this;
  }
  inline Trace& operator=(Trace&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Trace& default_instance() {
    return *internal_default_instance();
  }
  static inline const Trace* internal_default_instance() {
    return reinterpret_cast<const Trace*>(
        &_Trace_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Trace& a, Trace& b) { a.Swap(&b); }
  inline void Swap(Trace* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Trace* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Trace* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<Trace>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Trace& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Trace& from) { Trace::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Trace* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "dynamic_trace.Trace"; }

 protected:
  explicit Trace(::google::protobuf::Arena* arena);
  Trace(::google::protobuf::Arena* arena, const Trace& from);
  Trace(::google::protobuf::Arena* arena, Trace&& from) noexcept
      : Trace(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGpuDeviceFieldNumber = 6,
    kNameFieldNumber = 1,
    kNvbitVersionFieldNumber = 3,
    kBinaryVersionFieldNumber = 2,
    kAccelsimVersionFieldNumber = 4,
    kIsGatheredRegistersValuesFieldNumber = 5,
  };
  // map<int64, .dynamic_trace.gpu_device> gpu_device = 6;
  int gpu_device_size() const;
  private:
  int _internal_gpu_device_size() const;

  public:
  void clear_gpu_device() ;
  const ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>& gpu_device() const;
  ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>* mutable_gpu_device();

  private:
  const ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>& _internal_gpu_device() const;
  ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>* _internal_mutable_gpu_device();

  public:
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string nvbit_version = 3;
  void clear_nvbit_version() ;
  const std::string& nvbit_version() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_nvbit_version(Arg_&& arg, Args_... args);
  std::string* mutable_nvbit_version();
  PROTOBUF_NODISCARD std::string* release_nvbit_version();
  void set_allocated_nvbit_version(std::string* value);

  private:
  const std::string& _internal_nvbit_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nvbit_version(
      const std::string& value);
  std::string* _internal_mutable_nvbit_version();

  public:
  // int32 binary_version = 2;
  void clear_binary_version() ;
  ::int32_t binary_version() const;
  void set_binary_version(::int32_t value);

  private:
  ::int32_t _internal_binary_version() const;
  void _internal_set_binary_version(::int32_t value);

  public:
  // int32 accelsim_version = 4;
  void clear_accelsim_version() ;
  ::int32_t accelsim_version() const;
  void set_accelsim_version(::int32_t value);

  private:
  ::int32_t _internal_accelsim_version() const;
  void _internal_set_accelsim_version(::int32_t value);

  public:
  // bool is_gathered_registers_values = 5;
  void clear_is_gathered_registers_values() ;
  bool is_gathered_registers_values() const;
  void set_is_gathered_registers_values(bool value);

  private:
  bool _internal_is_gathered_registers_values() const;
  void _internal_set_is_gathered_registers_values(bool value);

  public:
  // @@protoc_insertion_point(class_scope:dynamic_trace.Trace)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 2,
      45, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Trace_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Trace& from_msg);
    ::google::protobuf::internal::MapField<Trace_GpuDeviceEntry_DoNotUse, ::int64_t, ::dynamic_trace::gpu_device,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        gpu_device_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr nvbit_version_;
    ::int32_t binary_version_;
    ::int32_t accelsim_version_;
    bool is_gathered_registers_values_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_trace_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Trace

// string name = 1;
inline void Trace::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Trace::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dynamic_trace.Trace.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Trace::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dynamic_trace.Trace.name)
}
inline std::string* Trace::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:dynamic_trace.Trace.name)
  return _s;
}
inline const std::string& Trace::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Trace::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Trace::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Trace::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dynamic_trace.Trace.name)
  return _impl_.name_.Release();
}
inline void Trace::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dynamic_trace.Trace.name)
}

// int32 binary_version = 2;
inline void Trace::clear_binary_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.binary_version_ = 0;
}
inline ::int32_t Trace::binary_version() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.Trace.binary_version)
  return _internal_binary_version();
}
inline void Trace::set_binary_version(::int32_t value) {
  _internal_set_binary_version(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.Trace.binary_version)
}
inline ::int32_t Trace::_internal_binary_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.binary_version_;
}
inline void Trace::_internal_set_binary_version(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.binary_version_ = value;
}

// string nvbit_version = 3;
inline void Trace::clear_nvbit_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nvbit_version_.ClearToEmpty();
}
inline const std::string& Trace::nvbit_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dynamic_trace.Trace.nvbit_version)
  return _internal_nvbit_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Trace::set_nvbit_version(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nvbit_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dynamic_trace.Trace.nvbit_version)
}
inline std::string* Trace::mutable_nvbit_version() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_nvbit_version();
  // @@protoc_insertion_point(field_mutable:dynamic_trace.Trace.nvbit_version)
  return _s;
}
inline const std::string& Trace::_internal_nvbit_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nvbit_version_.Get();
}
inline void Trace::_internal_set_nvbit_version(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nvbit_version_.Set(value, GetArena());
}
inline std::string* Trace::_internal_mutable_nvbit_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nvbit_version_.Mutable( GetArena());
}
inline std::string* Trace::release_nvbit_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dynamic_trace.Trace.nvbit_version)
  return _impl_.nvbit_version_.Release();
}
inline void Trace::set_allocated_nvbit_version(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nvbit_version_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.nvbit_version_.IsDefault()) {
          _impl_.nvbit_version_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dynamic_trace.Trace.nvbit_version)
}

// int32 accelsim_version = 4;
inline void Trace::clear_accelsim_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accelsim_version_ = 0;
}
inline ::int32_t Trace::accelsim_version() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.Trace.accelsim_version)
  return _internal_accelsim_version();
}
inline void Trace::set_accelsim_version(::int32_t value) {
  _internal_set_accelsim_version(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.Trace.accelsim_version)
}
inline ::int32_t Trace::_internal_accelsim_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accelsim_version_;
}
inline void Trace::_internal_set_accelsim_version(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accelsim_version_ = value;
}

// bool is_gathered_registers_values = 5;
inline void Trace::clear_is_gathered_registers_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_gathered_registers_values_ = false;
}
inline bool Trace::is_gathered_registers_values() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.Trace.is_gathered_registers_values)
  return _internal_is_gathered_registers_values();
}
inline void Trace::set_is_gathered_registers_values(bool value) {
  _internal_set_is_gathered_registers_values(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.Trace.is_gathered_registers_values)
}
inline bool Trace::_internal_is_gathered_registers_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_gathered_registers_values_;
}
inline void Trace::_internal_set_is_gathered_registers_values(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_gathered_registers_values_ = value;
}

// map<int64, .dynamic_trace.gpu_device> gpu_device = 6;
inline int Trace::_internal_gpu_device_size() const {
  return _internal_gpu_device().size();
}
inline int Trace::gpu_device_size() const {
  return _internal_gpu_device_size();
}
inline const ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>& Trace::_internal_gpu_device() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gpu_device_.GetMap();
}
inline const ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>& Trace::gpu_device() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:dynamic_trace.Trace.gpu_device)
  return _internal_gpu_device();
}
inline ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>* Trace::_internal_mutable_gpu_device() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.gpu_device_.MutableMap();
}
inline ::google::protobuf::Map<::int64_t, ::dynamic_trace::gpu_device>* Trace::mutable_gpu_device() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:dynamic_trace.Trace.gpu_device)
  return _internal_mutable_gpu_device();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace dynamic_trace


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_trace_2eproto_2epb_2eh
