// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warp.proto

#include "warp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dynamic_trace {
PROTOBUF_CONSTEXPR warp::warp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instructions_)*/{}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct warpDefaultTypeInternal {
  PROTOBUF_CONSTEXPR warpDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~warpDefaultTypeInternal() {}
  union {
    warp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 warpDefaultTypeInternal _warp_default_instance_;
}  // namespace dynamic_trace
static ::_pb::Metadata file_level_metadata_warp_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_warp_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_warp_2eproto = nullptr;

const uint32_t TableStruct_warp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::warp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::warp, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::dynamic_trace::warp, _impl_.instructions_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dynamic_trace::warp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dynamic_trace::_warp_default_instance_._instance,
};

const char descriptor_table_protodef_warp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nwarp.proto\022\rdynamic_trace\032\021instruction"
  ".proto\"D\n\004warp\022\n\n\002id\030\001 \001(\005\0220\n\014instructio"
  "ns\030\002 \003(\0132\032.dynamic_trace.instructionb\006pr"
  "oto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_warp_2eproto_deps[1] = {
  &::descriptor_table_instruction_2eproto,
};
static ::_pbi::once_flag descriptor_table_warp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_warp_2eproto = {
    false, false, 124, descriptor_table_protodef_warp_2eproto,
    "warp.proto",
    &descriptor_table_warp_2eproto_once, descriptor_table_warp_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_warp_2eproto::offsets,
    file_level_metadata_warp_2eproto, file_level_enum_descriptors_warp_2eproto,
    file_level_service_descriptors_warp_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_warp_2eproto_getter() {
  return &descriptor_table_warp_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_warp_2eproto(&descriptor_table_warp_2eproto);
namespace dynamic_trace {

// ===================================================================

class warp::_Internal {
 public:
};

void warp::clear_instructions() {
  _impl_.instructions_.Clear();
}
warp::warp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dynamic_trace.warp)
}
warp::warp(const warp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  warp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instructions_){from._impl_.instructions_}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:dynamic_trace.warp)
}

inline void warp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instructions_){arena}
    , decltype(_impl_.id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

warp::~warp() {
  // @@protoc_insertion_point(destructor:dynamic_trace.warp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void warp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instructions_.~RepeatedPtrField();
}

void warp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void warp::Clear() {
// @@protoc_insertion_point(message_clear_start:dynamic_trace.warp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instructions_.Clear();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* warp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .dynamic_trace.instruction instructions = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_instructions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* warp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dynamic_trace.warp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // repeated .dynamic_trace.instruction instructions = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_instructions_size()); i < n; i++) {
    const auto& repfield = this->_internal_instructions(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dynamic_trace.warp)
  return target;
}

size_t warp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dynamic_trace.warp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .dynamic_trace.instruction instructions = 2;
  total_size += 1UL * this->_internal_instructions_size();
  for (const auto& msg : this->_impl_.instructions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData warp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    warp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*warp::GetClassData() const { return &_class_data_; }


void warp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<warp*>(&to_msg);
  auto& from = static_cast<const warp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dynamic_trace.warp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.instructions_.MergeFrom(from._impl_.instructions_);
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void warp::CopyFrom(const warp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dynamic_trace.warp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool warp::IsInitialized() const {
  return true;
}

void warp::InternalSwap(warp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.instructions_.InternalSwap(&other->_impl_.instructions_);
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata warp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_warp_2eproto_getter, &descriptor_table_warp_2eproto_once,
      file_level_metadata_warp_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dynamic_trace::warp*
Arena::CreateMaybeMessage< ::dynamic_trace::warp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dynamic_trace::warp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
