// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warp.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_warp_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_warp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "instruction.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_warp_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_warp_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_warp_2eproto;
namespace dynamic_trace {
class warp;
struct warpDefaultTypeInternal;
extern warpDefaultTypeInternal _warp_default_instance_;
}  // namespace dynamic_trace
PROTOBUF_NAMESPACE_OPEN
template<> ::dynamic_trace::warp* Arena::CreateMaybeMessage<::dynamic_trace::warp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dynamic_trace {

// ===================================================================

class warp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dynamic_trace.warp) */ {
 public:
  inline warp() : warp(nullptr) {}
  ~warp() override;
  explicit PROTOBUF_CONSTEXPR warp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  warp(const warp& from);
  warp(warp&& from) noexcept
    : warp() {
    *this = ::std::move(from);
  }

  inline warp& operator=(const warp& from) {
    CopyFrom(from);
    return *this;
  }
  inline warp& operator=(warp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const warp& default_instance() {
    return *internal_default_instance();
  }
  static inline const warp* internal_default_instance() {
    return reinterpret_cast<const warp*>(
               &_warp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(warp& a, warp& b) {
    a.Swap(&b);
  }
  inline void Swap(warp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(warp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  warp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<warp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const warp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const warp& from) {
    warp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(warp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dynamic_trace.warp";
  }
  protected:
  explicit warp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInstructionsFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated .dynamic_trace.instruction instructions = 2;
  int instructions_size() const;
  private:
  int _internal_instructions_size() const;
  public:
  void clear_instructions();
  ::dynamic_trace::instruction* mutable_instructions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::instruction >*
      mutable_instructions();
  private:
  const ::dynamic_trace::instruction& _internal_instructions(int index) const;
  ::dynamic_trace::instruction* _internal_add_instructions();
  public:
  const ::dynamic_trace::instruction& instructions(int index) const;
  ::dynamic_trace::instruction* add_instructions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::instruction >&
      instructions() const;

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:dynamic_trace.warp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::instruction > instructions_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_warp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// warp

// int32 id = 1;
inline void warp::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t warp::_internal_id() const {
  return _impl_.id_;
}
inline int32_t warp::id() const {
  // @@protoc_insertion_point(field_get:dynamic_trace.warp.id)
  return _internal_id();
}
inline void warp::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void warp::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:dynamic_trace.warp.id)
}

// repeated .dynamic_trace.instruction instructions = 2;
inline int warp::_internal_instructions_size() const {
  return _impl_.instructions_.size();
}
inline int warp::instructions_size() const {
  return _internal_instructions_size();
}
inline ::dynamic_trace::instruction* warp::mutable_instructions(int index) {
  // @@protoc_insertion_point(field_mutable:dynamic_trace.warp.instructions)
  return _impl_.instructions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::instruction >*
warp::mutable_instructions() {
  // @@protoc_insertion_point(field_mutable_list:dynamic_trace.warp.instructions)
  return &_impl_.instructions_;
}
inline const ::dynamic_trace::instruction& warp::_internal_instructions(int index) const {
  return _impl_.instructions_.Get(index);
}
inline const ::dynamic_trace::instruction& warp::instructions(int index) const {
  // @@protoc_insertion_point(field_get:dynamic_trace.warp.instructions)
  return _internal_instructions(index);
}
inline ::dynamic_trace::instruction* warp::_internal_add_instructions() {
  return _impl_.instructions_.Add();
}
inline ::dynamic_trace::instruction* warp::add_instructions() {
  ::dynamic_trace::instruction* _add = _internal_add_instructions();
  // @@protoc_insertion_point(field_add:dynamic_trace.warp.instructions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dynamic_trace::instruction >&
warp::instructions() const {
  // @@protoc_insertion_point(field_list:dynamic_trace.warp.instructions)
  return _impl_.instructions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace dynamic_trace

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_warp_2eproto
